import { Course } from '../types';

export const COURSES: Course[] = [
  {
    id: '1',
    title: 'Mastering Digital Marketing 2024',
    description: 'Pelajari dasar-dasar SEO, SEM, dan manajemen media sosial untuk melejitkan bisnis Anda.',
    category: 'Digital Marketing',
    price: 499000,
    isFree: false,
    level: 'Pemula',
    duration: '12 Jam',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    instructor: 'Andi Pratama',
  },
  {
    id: '2',
    title: 'Menjadi Influencer Profesional',
    description: 'Bangun personal branding yang kuat dan dapatkan kerjasaman dengan brand ternama.',
    category: 'Influencer',
    price: 0,
    isFree: true,
    level: 'Pemula',
    duration: '5 Jam',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=800',
    instructor: 'Siska Amelia',
  },
  {
    id: '3',
    title: 'Streamer Essentials: Dari Nol ke Pro',
    description: 'Panduan lengkap setup streaming, interaksi audiens, dan monetisasi konten.',
    category: 'Streamer',
    price: 299000,
    isFree: false,
    level: 'Pemula',
    duration: '8 Jam',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800',
    instructor: 'Budi Gaming',
  },
  {
    id: '4',
    title: 'Analisis Bisnis Modern',
    description: 'Teknik analisis data untuk mengambil keputusan bisnis yang tepat dan strategis.',
    category: 'Business Analyst',
    price: 750000,
    isFree: false,
    level: 'Menengah',
    duration: '15 Jam',
    thumbnail: 'https://images.unsplash.com/photo-1454165833767-13143896796a?auto=format&fit=crop&q=80&w=800',
    instructor: 'Dr. Hendra Wijaya',
  },
  {
    id: '5',
    title: 'Data Science for Business',
    description: 'Gunakan machine learning untuk memprediksi tren pasar dan perilaku pelanggan.',
    category: 'Data Scientist',
    price: 0,
    isFree: true,
    level: 'Lanjutan',
    duration: '20 Jam',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
    instructor: 'Maya Kusuma',
  },
  {
    id: '6',
    title: 'Membangun Startup Digital',
    description: 'Dari ide hingga pitching. Pelajari cara memvalidasi produk dan mencari investor.',
    category: 'Startup',
    price: 1200000,
    isFree: false,
    level: 'Menengah',
    duration: '25 Jam',
    thumbnail: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&q=80&w=800',
    instructor: 'Rian CEO',
  },
  {
    id: '7',
    title: 'Remote Work Mastery',
    description: 'Cara mendapatkan pekerjaan remote di perusahaan global dengan gaji dollar.',
    category: 'Remote Work',
    price: 150000,
    isFree: false,
    level: 'Pemula',
    duration: '6 Jam',
    thumbnail: 'https://images.unsplash.com/photo-1587560699334-bea93391dcef?auto=format&fit=crop&q=80&w=800',
    instructor: 'Tono Freelance',
  },
];
